spring:
  zipkin:
    base-url: http://localhost:1234
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    root: error
    org:
      springframework:
        data: error
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
