spring:
  zipkin:
    base-url: http://localhost:1234
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
logging:
  file:
    path: /tmp/fb_webservice/${spring.application.name}/
    name: server_${server.port}.log
  level:
    root: debug
    org:
      springframework:
        data: debug  
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://Eur1:2222/eureka,http://Eur3:2223/eureka,http://Eur3:2224/eureka
